name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Git Config
        run: |
          git config --global user.email "pri1229nce@gmail.com"
          git config --global user.name "Prince-29"

      - name: Push to Hugging Face hub (with direct token)
        run: |
          git remote set-url origin https://Prince-29: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@huggingface.co/spaces/Prince-29/news-sentiment-analyzer
          git push --force origin main
