name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email pri1229nce@gmail.com
          git config --global user.name Prince-29
          git remote add hf https://Prince-29:${HF_TOKEN}@huggingface.co/spaces/Prince-29/news-sentiment-analyzer
          git push --force hf main
